
replicaCount: _REPLICAS_

image:
  repository: _REGISTRY_/_PROJECT_ID_/_APP_NAME_
  tag: _VERSION_
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  containerPort: _PORT_

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.com/health-checks: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 500m
    memory: 1000Mi
  requests:
    cpu: 500m
    memory: 1000Mi

livenessProbe:
  httpGet:
    path: /
    port: http
    scheme: HTTP
  initialDelaySeconds: 90
  periodSeconds: 30
  timeoutSeconds: 30
readinessProbe:
  httpGet:
    path: /
    port: http
    scheme: HTTP
  initialDelaySeconds: 90
  periodSeconds: 30
  timeoutSeconds: 30

nodeSelector: {}

tolerations: []

affinity: {}

configmap:
  NODE_ENV: Development
  VUE_APP_APP_VERSION: _VERSION_
  VUE_APP_PS_API_BASE_URL: http://portal-api._DEPLOYMENT_TYPE_.channelprecision.com
  VUE_APP_RW_API_BASE_URL: http://rw-api._DEPLOYMENT_TYPE_.channelprecision.com
  VUE_APP_RW_API_DEV_CLIENT_ID: 97ce55f3-18b2-4dec-80b6-50979a5d708b
  VUE_APP_RW_API_DEV_ACCESS_TOKEN:
  VUE_APP_MW_API_BASE_URL: http://mw-api._DEPLOYMENT_TYPE_.channelprecision.com
  VUE_APP_MW_DEV_ACCESS_TOKEN:
  VUE_APP_MW_DEV_CLIENT_ID: 97ce55f3-18b2-4dec-80b6-50979a5d708b
  VUE_APP_RA_API_BASE_URL: http://ra-api._DEPLOYMENT_TYPE_.channelprecision.com
  VUE_APP_RA_DEV_ACCESS_TOKEN:
  VUE_APP_RA_DEV_CLIENT_ID: 97ce55f3-18b2-4dec-80b6-50979a5d708b
  VUE_APP_DS_API_BASE_URL: http://ds-api._DEPLOYMENT_TYPE_.channelprecision.com
  VUE_APP_MT_API_BASE_URL: http://mt-api._DEPLOYMENT_TYPE_.channelprecision.com
  VUE_APP_DTD_API_BASE_URL: http://dtd-api._DEPLOYMENT_TYPE_.channelprecision.com
  VUE_APP_SKUF_API_BASE_URL: http://skuf-api._DEPLOYMENT_TYPE_.channelprecision.com
  VUE_APP_API_FIREBASE_KEY: _DEV_FIREBASE_KEY_
  VUE_APP_AUTH_DOMAIN: _DEV_AUTH_DOMAIN_
  VUE_APP_DATABASE_URL: _DEV_DATABASE_URL_
  VUE_APP_PROJECT_ID: _PROJECT_ID_
  VUE_APP_STORAGE_BUCKET: _DEV_STORAGE_BUCKET_
  VUE_APP_MESSAGING_SENDER_ID: _DEV_MESSAGING_SENDER_ID_
  VUE_APP_RW_APP_ID: _DEV_RW_APP_ID_
  VUE_APP_MW_APP_ID: _DEV_MW_APP_ID_
  VUE_APP_SDK_APP_CSS: https://storage.googleapis.com/ds-sdk/_SDK_VERSION_/dist/css/app.css
  VUE_APP_SDK_VENDOR_CSS: https://storage.googleapis.com/ds-sdk/_SDK_VERSION_/dist/css/chunk-vendors.css
  VUE_APP_SDK_VENDOR: https://storage.googleapis.com/ds-sdk/_SDK_VERSION_/dist/js/chunk-vendors.js
  VUE_APP_SDK_APP_JS: https://storage.googleapis.com/ds-sdk/_SDK_VERSION_/dist/js/app.js
  VUE_APP_PS_BUILD_APP: mwrw
  VUE_APP_RA_GOOGLE_REDIRECT_URL: http://matrix._DEPLOYMENT_TYPE_.channelprecision.com
  VUE_APP_API_KEY_EDITOR: _DEV_API_KEY_EDITOR_
  VUE_APP_BRANDING: Development Team
  VUE_APP_CP_PORTAL_WEB_URL: http://portal-web.qa.channelprecision.com
  VUE_APP_STR_SAMPLE_FILE: https://storage.googleapis.com/precise/dc/sell-through-report-import-sample.xlsx
  VUE_APP_MFN_PRIME_ORDERS_SAMPLE_FILE: https://storage.googleapis.com/precise/dc/mfn_prime_order_import_sample.xlsx
  VUE_APP_GOOGLE_CLIENT_ID: _GOOGLE_CLIENT_ID_
  VUE_APP_PS_GOOGLE_REDIRECT_URL: http://portal-web.qa.channelprecision.com
  VUE_APP_PS_GOOGLE_LOGIN_ENABLED: false
  VUE_APP_PS_AUTO_PICK_FIRST_CLIENT: true
  VUE_APP_PS_BACKGROUND: --matrix-bg
  VUE_APP_PS_ENABLE_MODERN_CSS: false
  VUE_APP_REGISTER_ENABLED: false
